sudo: required
language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - "$GCLOUD_CLUSTER_NAME=scarcity-cluster"
  - "$PGHOST=scarcity-pg"
  - "$PGUSER=postgres"
  - "$PGPASSWORD=postgres"
  - "$PGDB=postgres"
  - "$DOMAIN=scarcity.pessimistic-it.com"
  - "$CERT_EMAIL=achristianson@pessimistic-it.com"
  - "$REPO=andreaschristianson/scarcity"
  - "$REDIS_HOST=redis"
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: kpjhaml32xesJJ2KP2+ACGQ5FDcxryuAHUEsdxwBOUnVHvIo8h9iafPiyAn18rHFhgVOdQulDSOLCSySuiYNsE9JVZdSUA3L8Skf+CB6ncH+9s9zwZHw+orFAQgEbx94wPGnIIwkeStdzjnkXLqxGGWD3OhAPcuv+zjte9k5JhQgHlFLFhSja8qi+LcEDVKo1u+SlRX4I3Q8wYr3V92hU7bjd4FSBJ5DNpKk7T2cL5oqu1LaC+k9cGAg9EP8ucaYNSoyzj7B469nW+8RW+7QaupEvD7Ppfz4GsaYxOVltErCEfVf9TAo9zF186GrX83P3ijQHXFqDsD9PuNBLMIEuqu9kH9I2k38FVtj1C04gdgS0g8m5gQvHAi0N03e8v5Pu7D+EraxY3g0tygzLkF8B88ocXLiAC7KYzbT1RYXiORkk8qmWmhKNiMKEWbfv2NFVnKktmyTD2HzPIoD7ORgf3jvQenHfqfJOKBx2UijH5ahMIJW2USv7bJ0GFwvc5xBwSgv+uEEo4L7aCFw9syEvaLjb4HLhgPBlh/4rX+roDj9V9JZuuXjjH/e9AvN3OppdCtpbiAVlCjiXvNL2FJNfC68SYMVnyzHBPjPKXO+R1Y57XTcKhNYEGYpPZFkdM8n9M7l4CFME7MLxvxf1X1rYJpsoopZ4VuDzvxW9o0L5Es=
  - secure: Mp3mvlTsNu3la+0aWgoy8ARSwdeInyhmjvVKZJAXI8Ax/gSvpsEGBQBSSGBbeoHoMQsdZB1wjexHN81g8nWjRB61U/Qk2p/o5i6hNDpWGQ383YsuGUCaqpzxAWHCNVE1mXeefPGmKBBCSWf3vAjpFD9xh+XP7rc8j/SOuHWnxvzqCtki/X71dfJRGzifLXF7LL+nBvzuILk6kIQ1k50PJ8HmgS2jKN7xn9wCqyuYLCqt1aa+1a46oRtSJPT33bra3CwZ5mB0/Is7Y7z6Mtp//XuWupxzJ9yE6blVptA6Ua39yut4UYLxS/GuupAnZJ3E35/jB7novox/j4wi1mBfj9P5qPAShFz890PES6AV1OPvzRRHFlYGp8oQNojimPDKtyxqSE87Dbr9IDPMtGnVIgejrUC3hiZwH/iGiCI7yOV8lGY+HVIhz6IsSOZRAQTp2WzXGrzpqPaxPfGfpHZ0hMayRwpaTO2N+/b2nz2obb3IufAgMocCkHsDeT11vxQsaJUQUvLXN3ZQuma6Rw0qFqVhJo0yg1qO43IaKKmrCpt7wpIzLyHIbcdwJsHspNl/rAw1nm2p9YjDf4uPZQekzXoiFMqKtozN7p5wVRHNwMT2WDtvfNcEgqT+jY7GSJUrLQIgUCvegRCwpk6l+GHPtXqO5oU2nquWtyb4Ea9guP8=
  - secure: F0n9k4VG4gW0qsuTm36LL83Gc0RVjUKr6B8AwmNTZPYmaGagcETxWaOnwO9wllJ1nSLV7zRFUNuj1PkmgVzaGYJS22sI3Wv7mv+F7lNAWbcSihMiNOxI3CCIK5AxdRevz/th78m/1RG90tGVkLqDoooglg9mIEj1a8eqPFEAmwo+oWB7hRW5/ac3glGC6bC2m7/DWeG/9o7TuMytjJp2zrnKx9DrOoAIsmq4S5nvMYxmthw1HRFoFLsMsDjPFu2mU4/dnhohZXlyV51sr4UwXCbSb3XFWfN5pNG0XBNZk3BqPquNJ7bno8eGQ3stmQk/y/JHFzCkla64wk+sSHER+3mv8jNeyR+FRUkjEZDQcs0fCVcAxMkB0ilMapQ4lOcEaF/neO00YeWeD+bzZzmNDG6S+otq7u5AVRSnPMkVYiroLx3D1kpja49FsC0+2Deee/H44pS4A8H1IxcTTQiQRSau7MGT9yEKO1uArpqvo7Q7IRApd/GkFZjwqS7R536Xwxsj2zdh/U73ydA3FXeTPW9qRTPRgsDX/+uKAOjsAh0qnfyEE5JIoHaUjDtrTS6ydTsq6CvMXQj0LfCuz2qcq5Iw6OfVQYCLHptZrxuXHOcg0R+sT9qys64huDL3j8h9+UilwZCW8wJDd282go3lve6lnKtpgxzopBOXa5OFqvI=
  - secure: Jm4t6t+oHtcQfeonEIztBatKxah9ynvLJszDkR58w7ujPQcln51DTqb0Gd8W2yzLPWt4IIA8GZMMn9EVQ0zC/j0iYl4RjJEczi/ZJ/1YzmhlIKLDQ0sCcvCxqW6uz80TYY/YE3Hj+jYOySRjHfidevqcFPEYGhh1ZDzMoOfIZZrv9eIkIWUmS8Ofid2BpaGAlBeWYtJBY8BHQwTsif/NywstPeSeJXyCyfRgMgaQQBox4z0EDts7P/+qocYUxqYcYNdLCSLKEnpsHIHCEz5ZURsrlC0q1du4gKwk8/ComE79lFtaL7rBJcXsZ33k6nbxhJ5+KpDqr1v0AcNmf4nGlA+OpRaIslNenbOOlP2us9QF6cWFr1YBFvPQc4aTwfabi4XMGyodNRlgJDz+DknheNPII7V5K0p7a5Ze+3qgLdv6qE4n/tl8E1YvWOT+hFkglg0c01ZeuFiKplEta8ScuZ9XVXCVl9zKnan/1JXLcrfQPRAPZq945Uk8XmwfQe5zDtym3Pu+mikj4566YXifoXMa5DPd7ev1qAW6SuF9yRo/C36fYyvjb3MY8+0SURsQWCQzKHXy1KwHCNJ4LqHtY7ged9LXpzgwStsUKOm8aQ6GaL6QO66S1jf60apYa0+0wn4ffQYNfy7u8GB3o3nzLmDa7w9o4IpAxnEBu3QSrCE=
  - secure: Xhgr3LRz7MUuE9nlza4nOgnfUYt8Lhy/C6jW5pzJGihlBA5klfU9VYGxvptV1aALb5UbmS+HsZ9XTZPIZwiZGVLJcVPjTBHDqUuaMSa5UL50bzJv7jebjo2+sIsUluMyMo9relKaDebVLhQLPFuIrS+QZsx3Gcl9kvItq74tkaRE410dvKhokImgoPtfJJyU2bsp6fRxiEGczWvmOW7dYghrLaoo6NjHksnBllXlkkV26EzJp79DelvPhDFklIz3mroElYxagM7TXxXoeDKK775qAZbrEqUvP9hH6wOhkVe9IYgQzyf90eR3Y1pjsJHBrzNntCxQxxkpbXrCI1sG22ORhuzkQ2h9ehuQyHelLhU4/E5LcW7Vr8KCA/0mYKngVosU6ihGdnRozXKHgiSk+I24ZpjCNqKbmNk9qZ63GRBsAz+xFO8g1YngxjWb6v9Dd3+ye8BLbT+lHM+R/Qd3nvenKfgbu7Y+Rtb4GzWzxuhjNzzwbDlHRk8CzSFvMIiBYZUScuEg/A955fepAV4Hoo+5pwZxxZRA+ASgOOnEqktNzjxvVpfbfqiCuoWrN1xA1RkH1yAgOyh+urCBfstBVfdn0WIpFbNizmAomM+7CYliS0ZS8W27WqJ+Z0aNOSqud372668Qzl2AbtjS4a/o2/Shl2Rx3bYUc5ew66Zleqg=
before_install:
- python2 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL);
  fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
- docker --version
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; 
  curl https://sdk.cloud.google.com | bash; fi
install:
- npm install
script:
- npm test
- npm run build
- bash scripts/build-images.sh
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: bash scripts/deploy.sh
