kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: scarcity-app
spec:
  replicas: 2
  template:
    metadata:
      name: scarcity-template
      labels:
        app: scarcity
    spec:
      containers:
      - name: scarcity-container
        image: andreaschristianson/scarcity:$COMMIT
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 60
        ports:
        - name: scarcity-port
          containerPort: 80
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: 0
---
kind: Service
apiVersion: v1
metadata:
  name: scarcity-service
spec:
  type: LoadBalancer
  loadBalancerIP: "35.239.165.140"
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: scarcity
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: scarcity-redis
spec:
  template:
    metadata:
      name: redis-template
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:4-alpine
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
        ports:
        - containerPort: 6379
          name: redis-port
        resources:
          limits:
            cpu: "50m"
          requests:
            cpu: 0
